package Vista;

import Controlador.AccesoA;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author nacho
 */

public class Aplicacion extends javax.swing.JFrame {

    static int bandera = 0; //bandera estatica que se activa cuando se cierre sesión
    static String nombreEntrenador; //para guardar el nombre del entrenador que se usa la aplicacion en ese momento
    
    /**
     * Creates new form Aplicacion
     */
    public Aplicacion() {
        initComponents();
        AccesoA.conectar();
        desactivaComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldContraseña = new javax.swing.JTextField();
        jButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUsuario = new javax.swing.JMenu();
        jSubMenuPerfil = new javax.swing.JMenu();
        jSubMenuCerrarSesion = new javax.swing.JMenu();
        jMenuLista1a1 = new javax.swing.JMenu();
        jMenuAlta = new javax.swing.JMenu();
        jMenuJlist = new javax.swing.JMenu();
        jMenuAcercaDe = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 0, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("MasQueBasket");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Iniciar Sesión");

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNombre.setText("Nombre:");

        jLabelContraseña.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelContraseña.setText("Contraseña:");

        jButton.setText("Aceptar");
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        jMenuUsuario.setText("Usuario");

        jSubMenuPerfil.setText("Perfil");
        jMenuUsuario.add(jSubMenuPerfil);

        jSubMenuCerrarSesion.setText("Cerrar sesión");
        jSubMenuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubMenuCerrarSesionActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jSubMenuCerrarSesion);

        jMenuBar1.add(jMenuUsuario);

        jMenuLista1a1.setText("Ver jugadores");
        jMenuLista1a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLista1a1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuLista1a1);

        jMenuAlta.setText("Nueva convocatoria");
        jMenuBar1.add(jMenuAlta);

        jMenuJlist.setText("Ver partidos");
        jMenuBar1.add(jMenuJlist);

        jMenuAcercaDe.setText("Acerca de");
        jMenuAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAcercaDeActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuAcercaDe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelContraseña)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(jTextFieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelContraseña, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldContraseña, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        iniciarSesion();
    }//GEN-LAST:event_jButtonActionPerformed

    private void jSubMenuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubMenuCerrarSesionActionPerformed
        cerrarSesion();	       
    }//GEN-LAST:event_jSubMenuCerrarSesionActionPerformed

    private void jMenuAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAcercaDeActionPerformed
        JFrame frame = new JFrame();
        JOptionPane.showMessageDialog(frame,"Acerca de:");
    }//GEN-LAST:event_jMenuAcercaDeActionPerformed

    private void jMenuLista1a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLista1a1ActionPerformed
        
        pLista = new JPanelLista1a1();
        this.setContentPane(pLista);   
        //pLista.iniBotones();
        pack();
    }//GEN-LAST:event_jMenuLista1a1ActionPerformed

    public void iniciarSesion()
    {
        String nombre = jTextFieldNombre.getText();
        int contraseña = Integer.parseInt(jTextFieldContraseña.getText());
        
        String consulta1 = "select * from entrenador where nombre = '" + nombre +"' and contraseña = " + contraseña;
        
        if(AccesoA.consultaInicial(consulta1) == true)
        {
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame,"Inicio de sesión realizado con exito.");
            
            nombreEntrenador = nombre;
            
            jMenuBar1.setVisible(true);
            jLabel2.setVisible(false);
            jLabelNombre.setVisible(false);
            jLabelContraseña.setVisible(false);
            jTextFieldNombre.setVisible(false);
            jTextFieldContraseña.setVisible(false);
            jButton.setVisible(false);
            
        }else
        {
             JFrame frame = new JFrame();
             JOptionPane.showMessageDialog(frame,"Nombre o contraseña incorrectos.\nIntentalo de nuevo.");
             jTextFieldNombre.setText("");
             jTextFieldContraseña.setText("");
        }
    }
    
    public void cerrarSesion()
    {
        JFrame frame = new JFrame();
        JOptionPane.showMessageDialog(frame,"Se ha cerrado la sesión.");
        
        jMenuBar1.setVisible(false);
        jLabel2.setVisible(true);
        jLabelNombre.setVisible(true);
        jLabelContraseña.setVisible(true);
        jTextFieldNombre.setVisible(true);
        jTextFieldContraseña.setVisible(true);
        jButton.setVisible(true);
        AccesoA.cerrar();
    }
    
    public void desactivaComponentes()
    {
        jMenuBar1.setVisible(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplicacion().setVisible(true);
            }
        });
        
    }
    
    private Vista.JPanelLista1a1 pLista = new JPanelLista1a1();
    private Vista.JPanelAltaConvocatoria pAlta = new JPanelAltaConvocatoria();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JMenu jMenuAcercaDe;
    private javax.swing.JMenu jMenuAlta;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuJlist;
    private javax.swing.JMenu jMenuLista1a1;
    private javax.swing.JMenu jMenuUsuario;
    private javax.swing.JMenu jSubMenuCerrarSesion;
    private javax.swing.JMenu jSubMenuPerfil;
    private javax.swing.JTextField jTextFieldContraseña;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}

/*
import java.sql.*;
public class EjemploAccesoBD8 {
    public static void main(String[] args) {
        Connection conexion = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
       conexion =
       DriverManager.getConnection("jdbc:mysql://localhost/prueba?useServerPrepStmts=true", "root", "1daw");
       PreparedStatement ps = conexion.prepareStatement("INSERT INTO contactos values (null,?,?,?)");                  
           //Asigno al primer ? el String "Leopoldo".
           //Corresponde al campo nombre de tipo VARCHAR
            ps.setString(1, "Leopoldo");
            // Asigno al segundo ? el String "Pelayo".
            //Corresponde al campo apellidos de tipo VARCHAR
            ps.setString(2, "Pelayo");
            // Asigno al tercer ? el String "987876509".
            //Corresponde al campo telefono de tipo VARCHAR
            ps.setString(3, "999878765");
            // Se ejecuta la operación.
            ps.executeUpdate();
        } catch (SQLException e) {
            System.out.println(e.toString());
        } catch (ClassNotFoundException e) {
            System.out.println(e.toString());
        } finally {
            try {
                if (conexion != null) {
                    conexion.close();
                }
            } catch (SQLException ex) {
                System.out.println(ex.toString());
            }
        }
    }
}
*/